POST  http://view.bk.cloudns.cc:8080/admin/v1/login
HEAD: "Content-Type: applications/json"

{
    "email":"lq@163.com",
    "password":"qweasdzxc"
}

### to login paypal site

post https://api.sandbox.paypal.com/v1/oauth2/token
Content-Type: applications/json
Accept-Language: en-US
Authorization: Basic AbOMcM4iaf0PYKGgOFCktDD-Rqzpn7R_r2yPfwbopgCLYkBLXkD45c1qejwVX2BrBSxVQgz3_QlU7iFn:EKxToL0apcJ7HOAryLeFkyP9JRWuw-p8pMj9M5N3Y1Ee8tsUDFgRv1wA_3hIjRMiHqrmbQu12KW_Noys

grant_type=client_credentials

### 

GET https://api.sandbox.paypal.com/v1/notifications/webhooks 
Content-Type: application/json 
Authorization: Bearer A21AAKHo9PRmJmkTowrW67Q87XoauHbNv5VMyZ7pS53_y1ZtSoPa1yLKRDYh3m3uxa_oEdI8epm8xKeafyIGhkryNh6W3TqHQ

### 

GET https://api.sandbox.paypal.com/v1/reporting/transactions?&start_date=2020-11-01T00:00:00-0700&end_date=2020-12-02T23:59:59-0700&page=1&transaction_id=4CE4044950003234R
Content-Type: application/json
Authorization: Bearer A21AAJp0dZ7s1fatFijU_e6ISJ2lRUvhJJNbayNW9WQTICLYxbAQDTqJs5ubcjCA2oyYWQz4T848NP7UfBTsppvWWkF3AUz-A

###

GET https://api.sandbox.paypal.com/v1/reporting/transactions?&start_date=2020-11-01T00:00:00-0700&end_date=2020-12-02T23:59:59-0700&page=1&transaction_amount=250247
Content-Type: application/json
Authorization: Bearer A21AAKHo9PRmJmkTowrW67Q87XoauHbNv5VMyZ7pS53_y1ZtSoPa1yLKRDYh3m3uxa_oEdI8epm8xKeafyIGhkryNh6W3TqHQ

###
GET https://api.sandbox.paypal.com/v2/checkout/orders/8K9173018M398481Y
Content-Type: application/json
Authorization: Bearer A21AAG4tOxgh9wz1Q44ieUZgPyI0YOAIv2qvFbS7KEe-swpq1dxS7boi18Fkd-Vl5cPnM0IYJue0tPp7a1PrkJW4o_UjazzSA

###

GET https://api.sandbox.paypal.com/v2/payments/captures/1BA013359L365131R
Content-Type: application/json
Authorization: Bearer A21AAHhaJi5v-rs5F16L26I1xhelfJHr62BYPScnlwduSqm22n1tIvNfug0BdRgGLPzy-RNhBPUJHl5j39YXKByqVcNGTakyg

###
https://api.sandbox.paypal.com/v1/reporting/transactions?end_date=2020-12-02T20%3A01%3A06%2B08%3A00&fields=all&page=1&page_size=5&start_date=2020-11-01T20%3A01%3A06%2B08%3A00&transaction_amount=129224
Content-Type: application/json
Authorization: Bearer A21AAJp0dZ7s1fatFijU_e6ISJ2lRUvhJJNbayNW9WQTICLYxbAQDTqJs5ubcjCA2oyYWQz4T848NP7UfBTsppvWWkF3AUz-A


https://api.sandbox.paypal.com/v1/payments/payment?count=10&start_index=0&sort_by=create_time 
Content-Type: application/json
Authorization: Bearer A21AAF7Dmsvq96UHaH0bLCn-pHOg8laYivs8R0HiZTYJ8oacLsfEkP__DrnWPRacC6oFcXOenVzW_6wQY-cefjs6g200rvVnQ

###

GET https://api.sandbox.paypal.com/v1/notifications/webhooks/8GJ36790KA152731C
Content-Type: application/json
Authorization: Bearer A21AAF7Dmsvq96UHaH0bLCn-pHOg8laYivs8R0HiZTYJ8oacLsfEkP__DrnWPRacC6oFcXOenVzW_6wQY-cefjs6g200rvVnQ


### create a order capture

POST https://api.sandbox.paypal.com/v2/checkout/orders 
Content-Type: application/json
Authorization: Bearer A21AAF7Dmsvq96UHaH0bLCn-pHOg8laYivs8R0HiZTYJ8oacLsfEkP__DrnWPRacC6oFcXOenVzW_6wQY-cefjs6g200rvVnQ

{
  "intent": "CAPTURE",
  "purchase_units": [
    {
      "amount": {
        "currency_code": "USD",
        "value": "100.00"
      }
    }
  ]
}

###

POST https://api.sandbox.paypal.com/v2/checkout/orders
Content-Type: application/json
Authorization: Bearer A21AAEl-QGUtyHPyHaS0I854JT129xmhK9BjIs0RaeBAUaaNsBYUjKY-B3KYl6iW_FMXBzTo9ttX6ej047kM9OYBuske9sdyg
Prefer:return=representation

{
  "intent": "CAPTURE",
  "application_context":{
    "brand_name":"aaaaaa 坏了",
    "landing_page":"LOGIN",
    "locale":"de-DE"
  },
  "purchase_units": [
    {
      "amount": {
        "currency_code": "USD",
        "value": "100.00"
      }
    }
  ]
}

###

POST http://view.bk.cloudns.cc:8080/payment/paypal/pay
Content-Type: application/json

{
  "payer":"paypal",
  "email":"jihua.gao@mgmail.com",
  "method":"credict",
  "amount":{
        "value": "30.11",
        "currency_code": "USD"
  },
  "shipping": {
      "recipient_name": "Brian Robinson",
      "line1": "4th Floor",
      "line2": "Unit #34",
      "city": "San Jose",
      "country_code": "US",
      "postal_code": "95131",
      "phone": "011862212345678",
      "state": "CA"
    },
  "item_list": [
          {
            "name": "hat",
            "description": "Brown hat.",
            "unit_amount": "5",
            "quantity": "5",
            "price": "30.11",
            "currency": "USD"
          }
  ]  
}

###


POST http://view.bk.cloudns.cc:8080/payment/paypal/pay
Content-Type: application/json

{
  "payer":"paypal",
  "email":"e_raeb@yahoo.com",
  "comments":"yyuyyyyyyuyyuyu",
  "item_list": [
        {
          "amount":{
                "value": "21.11",
                "currency_code": "USD",
                "breakdown":{
                  "item_total":{
                    "currency_code":"USD",
                    "value":"21.11"
                  }
                }
          },
          "invoice_id":"xzzzzzz2323",
          "description":"note",
          "shipping": {
            "name": {
              "full_name":"Brian Robinson"
            },
            "address":{
              "address_line_1": "4th Floor",
              "address_line_2":"",
              "admin_area_2": "San Jose",
              "admin_area_1": "CA",
              "country_code": "US",
              "postal_code":"300984"
            }
          },
          "items":[
          {
            "name": "hat111",
            "description": "Brown hat. for human",
            "unit_amount":{
              "currency_code":"USD",
              "value":"0.5"
            },
            "quantity": "2",
            "category": "DIGITAL_GOODS"
          },
          {
            "name": "hat",
            "description": "n",
            "unit_amount":{
              "currency_code":"USD",
              "value":"10"
            },
            "quantity": "1",
            "category": "DIGITAL_GOODS"
          },
          {
            "name": "handbag222",
            "description": "Black handbag. for spagati",
            "quantity": "1",
            "unit_amount":{
              "currency_code":"USD",
              "value":"10.11"
            },
            "category": "DIGITAL_GOODS"
          }
          ]
        }
  ] 
}

###

POST http://127.0.0.1:8080/payment/paypal/pay
Content-Type: application/json

{
  "payer":"paypal",
  "email":"e_raeb@yahoo.com",
  "comments":"sdm,dssfds sdfsdf",
  "method":"BILLING",
  "item_list": [
    {
     "amount":{
        "value": "30",
        "currency_code": "USD",
        "breakdown":{
          "item_total":{
            "currency_code":"USD",
            "value":"30"
          }
        }
  },
  "shipping": {
      "name": {
              "full_name":"geRobinson"
            },
      "address":{
              "address_line_1": "4th Floor",
              "address_line_2":"",
              "admin_area_2": "San Jose",
              "admin_area_1": "CA",
              "country_code": "DE",
              "postal_code":"300984"
            }
    },
     "items":[      { 
            "name": "hat111",
            "description": "Brown hat.",
            "unit_amount":{
              "currency_code":"USD",
              "value":"3"
            },
            "quantity": "5",
            "category": "DIGITAL_GOODS"
          },
          {
            "name": "handbag222",
            "description": "Black handbag.",
            "quantity": "1",
            "unit_amount":{
              "currency_code":"USD",
              "value":"15"
            },
            "category": "DIGITAL_GOODS"
          }
     ]
    }
  ]  
}


###

POST http://127.0.0.1:8080/payment/paypal/pay
Content-Type: application/json

{
  "email": "ce",
  "payer": "paypal",
  "comments": "12",
  "method": "BILLING",
  "item_list": [
    {
      "reference_id": "",
      "items": [
          {
            "name": "Exalted Orb",
            "quantity": "2",
            "method": "BILLING",
            "unit_amount": {
              "currency_code": "USD",
              "value": "0.90"
            },
            "description": "mm"
          }
        ],
      "amount": {
        "currency_code": "USD",
        "value": "1.80",
        "breakdown": {
          "item_total": {
            "currency_code": "USD",
            "value": "1.80"
          }
        },
        
        "customer_id": "",
        "description": "21facebook"
      }
    }
  ]
}


###

POST https://support.bk.cloudns.cc:8081/admin/v1/login 
Content-Type: applications/json

{"email":"lq@163.com","password":"qweasdzxc"}

###
POST https://support.bk.cloudns.cc:8081/api/v1/config
Content-Type: applications/json


###


POST http://view.bk.cloudns.cc:8080/admin/v1/user/update  
Content-Type: applications/json
Set-Cookie: lqcms_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOm51bGwsImNvdW50cnkiOiIiLCJleHAiOiIyMDIwLTA3LTA0VDE0OjQ3OjQ0Ljc2NjAwOTI4MyswODowMCIsImlhdCI6bnVsbCwiaXNzIjpudWxsLCJqdGkiOm51bGwsIm5iZiI6bnVsbCwic3ViIjpudWxsLCJ1c2VyIjoibHFAMTYzLmNvbSJ9.6tizq2Qw3GulIZE7KBo5kmyFBdrCWIcMamHBERUP1kY; Path=/; Expires=Sat, 04 Jul 2020 06:47:44 GMT

{"email":"408006570@qq.com","password":"abcd1234","new_password":"sss111"}

###


POST http://sandbox.payssion.com/api/v1/payment/create
Content-Type: applications/json

{"api_key":"sandbox_5dea43e2a2a8e257",
"pm_id":"dotpay_pl",
"amount":"1",
"currency":"USD",
"description":"payment description",
"order_id":"1234",
"api_sig":"add918417e849e1e8c350c3babe3c6d7"
}


###


POST http://view.bk.cloudns.cc:8080/payment/payssion/pay
Content-Type: applications/json

{
"pm_id":"dotpay_pl",
"amount":"221",
"currency":"USD",
"description":"神奇宝贝",
"payer_email":"18901882538@189.cn"
}


###
https://api.sandbox.paypal.com/v1/identity/oauth2/userinfo?schema=paypalv1.1 \
-H "Content-Type: application/json" \
-H "Authorization: Bearer Access-Token"

### 

POST http://view.bk.cloudns.cc:8080/payment/payssion/pay
Content-Type: applications/json

{
"pm_id":"dotpay_pl",
"amount":"3.3",
"currency":"USD",
"description":"天降大人"
}

### 
POST http://view.bk.cloudns.cc:8080/payment/payssion/notify
Content-Type: applications/json

{
  "app_name": "eshop",
"pm_id": "dotpay_pl",
"transaction_id": "T527553600236576",
"order_id" :"cf6ff489dc1cb799987fa989c6f41d45",
"amount":"1.1",
"currency":"USD",
"state":"completed",
"notify_sig": "addDSAasfsafdaasdf"
}

### 

POST http://127.0.0.1:8080/payment/paypal/notify
Content-Type: application/json

{
  "id": "WH-58D329510W468432D-8HN650336L201105X",
  "create_time": "2019-02-14T21:50:07.940Z",
  "resource_type": "capture",
  "event_type": "PAYMENT.CAPTURE.COMPLETED",
  "summary": "Payment completed for $ 2.51 USD",
  "resource": {
    "amount": {
      "currency_code": "USD",
      "value": "2.51"
    },
    "seller_protection": {
      "status": "ELIGIBLE",
      "dispute_categories": [
        "ITEM_NOT_RECEIVED",
        "UNAUTHORIZED_TRANSACTION"
      ]
    },
    "update_time": "2019-02-14T21:49:58Z",
    "create_time": "2019-02-14T21:49:58Z",
    "final_capture": true,
    "seller_receivable_breakdown": {
      "gross_amount": {
        "currency_code": "USD",
        "value": "2.51"
      },
      "paypal_fee": {
        "currency_code": "USD",
        "value": "0.37"
      },
      "net_amount": {
        "currency_code": "USD",
        "value": "2.14"
      }
    },
    "links": [
      {
        "href": "https://api.paypal.com/v2/payments/captures/27M47624FP291604U",
        "rel": "self",
        "method": "GET"
      },
      {
        "href": "https://api.paypal.com/v2/payments/captures/27M47624FP291604U/refund",
        "rel": "refund",
        "method": "POST"
      },
      {
        "href": "https://api.paypal.com/v2/payments/authorizations/7W5147081L658180V",
        "rel": "up",
        "method": "GET"
      }
    ],
    "id": "27M47624FP291604U",
    "status": "COMPLETED"
  },
  "links": [
    {
      "href": "https://api.paypal.com/v1/notifications/webhooks-events/WH-58D329510W468432D-8HN650336L201105X",
      "rel": "self",
      "method": "GET",
      "encType": "application/json"
    },
    {
      "href": "https://api.paypal.com/v1/notifications/webhooks-events/WH-58D329510W468432D-8HN650336L201105X/resend",
      "rel": "resend",
      "method": "POST",
      "encType": "application/json"
    }
  ],
  "event_version": "1.0",
  "resource_version": "2.0"
}

###

POST https://support.bk.cloudns.cc:8081/payment/skrill/pay
Content-Type: application/json

{
"amount":"23.21",
"currency":"EUR",
"description":"riptifdsafsafasfdsadfsafdon",
"payer_email":"18901882538@189.cn",
"address":"天2323色一万",
"city":"上海3434",
"country":"打算列",
"description":"阿斯顿麻木"
}


###

POST  https://pay.skrill.com/?prepare_only=1&pay_to_email=demoqco@sun-fish.com&language=EN&amount=3.2&currency=GBP&detail1_description=helloworld&detail1_text=mm
Content-Type: application/x-www-form-urlencoded
      

														<a target="_blank" href="https://www.skrill.com/en/business/integration/">
															<img src="https://www.skrill.com/fileadmin/content/images/brand_centre/Payment_Options_by_Skrill/skrill-powered-visa_120x60.png" alt="Visa by Skrill" title="Visa by Skrill"/>
														</a>

												

### 

Post https://api.smtp2go.com/v3/allowed_senders/add
Content-Type: application/json

{
  "api_key": "api-E408790EAED711EA8BC0F23C91C88F4E",
  "allowed_senders": ["support@bk.cloudns.cc"]
}

### 

Post https://api.smtp2go.com/v3/allowed_senders/view


"api_key"="api-E408790EAED711EA8BC0F23C91C88F4E",

### 

GET http://api.ipstack.com/134.201.250.155?access_key=16fb28ea154934b40d30858c34a28ca4

###

Get https://support.bk.cloudns.cc:8081/admin/v1/contents/search?type=Product&count=-1&q=Path of Exile
Content-Type: application/json

###

Get http://127.0.0.1:8080/admin/v1/contents/search?type=Game&count=-1&q=game-测试&filter=!logo:1
Content-Type: application/json


###


POST http://127.0.0.1:8080/payment/payssion/dopay
Content-Type: applications/json

{
"payment":"payssion",
"payment_channel":"dotpay_pl",
"amount":221,
"currency":"USD",
"language":"En",
"email":"jihua.gao@gmail.com",
"request_info":"神奇宝贝大力及关系v2",
"payer_email":"18901882538@189.cn",
"contract_info":"1123345566",
"item_list":[
  {"game":"abc","Server":"server1","product":"东南一家","unit_price":1123,"quantity":1000,"category":"A类"},
  {"game":"etf","Server":"server2","product":"妈妈小一家","unit_price":113,"quantity":1000,"category":"B类"}
]
}

####


POST http://127.0.0.1:8080/payment/skrill/dopay
Content-Type: applications/json

{
"payment":"skrill",
"payment_channel":"dotpay_pl",
"currency":"EUR",
"description":"riptifdsafsafasfdsadfsafdon",
"email":"18901882538@189.cn",
"address":"天2323色一万",
"city":"上海3434",
"country":"打算列",
"amount":12.3,
"language":"En",
"request_info":"skrill神奇宝贝大力及关系v2",
"contact_info":"1123345566ss",
"item_list":[
  {"game":"abc","Server":"server1","product":"东南一家","unit_price":1123,"quantity":1000,"category":"A类"},
  {"game":"etf","Server":"server2","product":"妈妈小一家","unit_price":113,"quantity":1000,"category":"B类"}
]
}

###

POST http://127.0.0.1:8080/payment/paypal/dopay
Content-Type: applications/json

{
"payment":"paypal",
"payment_channel":"BILLING",
"currency":"USD",
"description":"dwewewewe",
"email":"18901882538@189.cn",
"address":"天2323色一万",
"city":"上海3434",
"country":"打算列",
"amount":12.3,
"language":"En",
"request_info":"skrill神奇宝贝大力及关系v2",
"contact_info":"1123345566ss",
"item_list":[
  {"game":"abc123","Server":"server1","product":"东南一家","unit_price":1123,"quantity":1000,"category":"A类"},
  {"game":"etf345","Server":"server2","product":"妈妈小一家","unit_price":113,"quantity":1000,"category":"B类"}
]
}
###
GET http://127.0.0.1:8080/payment/orderid/1234567
Content-Type: applications/json

###


POST http://127.0.0.1:8080/payment/paypal/dopay
Content-Type: applications/json

{"payment":"paypal","payment_channel":"BILLING",
"amount":17.98,
"currency":"USD",
"language":"UK",
"email":"408006570@qq.com",
"request_info":"2112",
"contract_info":"facebook12",
"item_list":[
  {"game":"Neverwinter Online","server":"PC","unit_price":8.99,"product":"NWO AD*1","quantity":2}
  ],
"sub_total":17.98,
"city":"",
"country":"",
"first_name":"",
"last_name":"",
"phone":"18352862123",
"coupon_code":"",
"coupon_value":0,
"payment_fee":0.018,
"address":"",
"description":"",
"status":""}

###
POST http://127.0.0.1:8080/payment/paypal/dopay
Content-Type: applications/json

{"payment":"paypal",
"payment_channel":"BILLING",
"amount":18,
"currency":"USD",
"language":"UK",
"email":"408006570@qq.com",
"request_info":"12",
"contract_info":"whatsappcehi",
"item_list":[
  {
    "game":"Neverwinter Online",
    "server":"PC",
    "unit_price":8.99,
    "product":"NWO AD*1",
    "quantity":2}
],
"sub_total":17.98,
"city":"",
"country":"",
"first_name":"",
"last_name":"",
"phone":"18352862123",
"coupon_code":"",
"coupon_value":0,
"payment_fee":0.02,
"logo_url":"",
"address":"",
"description":"",
"status":""
}

###


POST https://support.bk.cloudns.cc:8081/payment/paypal/dopay
Content-Type: applications/json

{"payment":"paypal",
"payment_channel":"BILLING",
"amount":18,
"currency":"USD",
"language":"UK",
"email":"408006570@qq.com",
"request_info":"12",
"contract_info":"whatsappcehi",
"item_list":[
  {
    "game":"Neverwinter Online",  
    "server":"PC",
    "unit_price":8.99,
    "product":"NWO AD*1",
    "quantity":2}
],
"sub_total":17.98,
"city":"",
"country":"",
"first_name":"",
"last_name":"",
"phone":"18352862123",
"coupon_code":"",
"coupon_value":0,
"payment_fee":0.02,
"logo_url":"",
"address":"",
"description":"",
"status":""
}

###

POST http://127.0.0.1:8080/payment/paypal/dopay
Content-Type: applications/json

{"payment":"paypal",
"payment_channel":"BILLING",
"amount":18,
"currency":"USD",
"language":"UK",
"email":"408006570@qq.com",
"request_info":"12",
"contract_info":"whatsappcehi",
"item_list":[
  {
    "game":"Neverwinter Online",  
    "server":"PC",
    "unit_price":8.99,
    "product":"NWO AD*1",
    "quantity":2}
],
"sub_total":17.98,
"city":"",
"country":"",
"first_name":"",
"last_name":"",
"phone":"18352862123",
"coupon_code":"",
"coupon_value":0,
"payment_fee":0.02,
"logo_url":"",
"address":"",
"description":"",
"status":""
}

###

POST https://support.bk.cloudns.cc:8081/admin/v1/content/update?type=Product&id=38
Content-Type: applications/json

{ "Unit":"pcs",
  "customerLabel":"PSN",
  "description":"",
  "discount":"4,Sto PC",
  "game":"9,Star Trek Online",
  "hintImage":"",
  "hintText":"abc",
  "id":38,
  "miniNumber":1,
  "name":"Master Key - PS4",
  "online":true,
  "price":6.99,
  "slug":"product-master-key---pc(复制)",
  "sname":"Master Key - PS4",
  "stock":999999,
  "timestamp":0,
  "type":"item,item",
  "updated":1605588332310,
  "uuid":"734d6c32-d940-4fd6-a3c1-fea2adafa35d"
  }

###


POST http://127.0.0.1:8080/admin/v1/content/update?type=Product&id=38
Content-Type: applications/json

{ "Unit":"pcs",
  "customerLabel":"PSN",
  "description":"",
  "discount":"4,Sto PC",
  "game":"9,Star Trek Online",
  "hintImage":"--remove--",
  "hintText":"abc",
  "id":38,
  "miniNumber":1,
  "name":"Master Key - PS4",
  "online":true,
  "price":6.99,
  "slug":"product-master-key---pc(复制)",
  "sname":"Master Key - PS4",
  "stock":999999,
  "timestamp":0,
  "type":"item,item",
  "updated":1605588332310,
  "uuid":"734d6c32-d940-4fd6-a3c1-fea2adafa35d"
  }

###

POST https://support.bk.cloudns.cc:8081/payment/static/dopay
Content-Type: applications/json

{"payment":"static",
"payment_channel":"Wechat",
"amount":1,
"currency":"USD",
"language":"UK",
"email":"408006570@qq.com",
"request_info":"12",
"contract_info":"saiQidunasm",
"item_list":[
  {
    "game":"Neverwinter Online",  
    "server":"PC",
    "unit_price":0.5,
    "product":"dmcmd",
    "quantity":2}
],
"sub_total":1,
"city":"",
"country":"",
"first_name":"",
"last_name":"",
"phone":"18352862123",
"coupon_code":"",
"coupon_value":0,
"payment_fee":0.02,
"logo_url":"",
"address":"",
"description":"",
"status":""
}

###

POST http://127.0.0.1:8080/payment/static/dopay
Content-Type: applications/json

{"payment":"static",
"payment_channel":"Wechat",
"amount":18,
"currency":"USD",
"language":"UK",
"email":"408006570@qq.com",
"request_info":"12",
"contract_info":"whatsappcehi",
"item_list":[
  {
    "game":"Neverwinter Online",  
    "server":"PC",
    "unit_price":8.99,
    "product":"NWO AD*1",
    "quantity":2
  }
],
"sub_total":17.98,
"city":"",
"country":"",
"first_name":"",
"last_name":"",
"phone":"18352862123",
"coupon_code":"",
"coupon_value":0,
"payment_fee":0.02,
"logo_url":"",
"address":"",
"description":"",
"status":""
}
###

POST http://127.0.0.1:8080/payment/payssion/dopay
Content-Type: applications/json

{"payment":"payssion",
"payment_channel":"dotpay_pl",
"amount":18,
"currency":"USD",
"language":"UK",
"email":"408006570@qq.com",
"request_info":"12",
"contract_info":"whatsappcehi",
"item_list":[
  {
    "game":"Neverwinter Online",  
    "server":"PC",
    "unit_price":8.99,
    "product":"NWO AD*1",
    "quantity":2
  }
],
"sub_total":17.98,
"city":"",
"country":"",
"first_name":"",
"last_name":"",
"phone":"18352862123",
"coupon_code":"",
"coupon_value":0,
"payment_fee":0.02,
"logo_url":"",
"address":"",
"description":"",
"status":""
}
###

POST https://support.bk.cloudns.cc/payment/payssion/dopay
Content-Type: applications/json

{"payment":"payssion",
"payment_channel":"paysafecard",
"amount":18,
"currency":"USD",
"language":"UK",
"email":"408006570@qq.com",
"request_info":"12",
"contract_info":"whatsappcehi",
"item_list":[
  {
    "game":"Neverwinter Online",  
    "server":"PC",
    "unit_price":8.99,
    "product":"NWO AD*1",
    "quantity":2
  }
],
"sub_total":17.98,
"city":"",
"country":"",
"first_name":"",
"last_name":"",
"phone":"18352862123",
"coupon_code":"",
"coupon_value":0,
"payment_fee":0.02,
"logo_url":"",
"address":"",
"description":"",
"status":""
}
POST http://127.0.0.1:8080/payment/static/return

###


POST http://127.0.0.1:8080/payment/paypal/notify
Content-Type: applications/json

{
  "id": "WH-0H899151972497740-0A372964B8753370B",
  "event_version": "1.0",
  "create_time": "2020-11-27T11:43:33.731Z",
  "resource_type": "checkout-order",
  "resource_version": "2.0",
  "event_type": "CHECKOUT.ORDER.APPROVED",
  "summary": "An order has been approved by buyer",
  "resource": {
    "update_time": "2020-11-27T11:43:22Z",
    "create_time": "2020-11-27T11:37:07Z",
    "purchase_units": [
      {
        "reference_id": "default",
        "amount": {
          "currency_code": "USD",
          "value": "1501.49"
        },
        "payee": {
          "email_address": "sb-opduc1687278@business.example.com",
          "merchant_id": "VRS5GBP9ETXXU",
          "display_data": {
            "brand_name": "EGPAL Game"
          }
        },
        "invoice_id": "20201263800",
        "shipping": {
          "name": {
            "full_name": "gao jihua"
          },
          "address": {
            "address_line_1": "23 Zhongshan East 1 Road",
            "admin_area_2": "Shanghai",
            "admin_area_1": "Shanghai",
            "postal_code": "200002",
            "country_code": "C2"
          }
        },
        "payments": {
          "captures": [
            {
              "id": "6UG29005VY542582H",
              "status": "COMPLETED",
              "amount": {
                "currency_code": "USD",
                "value": "1501.49"
              },
              "final_capture": true,
              "seller_protection": {
                "status": "ELIGIBLE",
                "dispute_categories": [
                  "ITEM_NOT_RECEIVED",
                  "UNAUTHORIZED_TRANSACTION"
                ]
              },
              "seller_receivable_breakdown": {
                "gross_amount": {
                  "currency_code": "USD",
                  "value": "1501.49"
                },
                "paypal_fee": {
                  "currency_code": "USD",
                  "value": "58.86"
                },
                "net_amount": {
                  "currency_code": "USD",
                  "value": "1442.63"
                }
              },
              "invoice_id": "20201102654",
              "links": [
                {
                  "href": "https://api.sandbox.paypal.com/v2/payments/captures/6UG29005VY542582H",
                  "rel": "self",
                  "method": "GET"
                },
                {
                  "href": "https://api.sandbox.paypal.com/v2/payments/captures/6UG29005VY542582H/refund",
                  "rel": "refund",
                  "method": "POST"
                },
                {
                  "href": "https://api.sandbox.paypal.com/v2/checkout/orders/3L413397YW525633X",
                  "rel": "up",
                  "method": "GET"
                }
              ],
              "create_time": "2020-11-27T11:43:22Z",
              "update_time": "2020-11-27T11:43:22Z"
            }
          ]
        }
      }
    ],
    "links": [
      {
        "href": "https://api.sandbox.paypal.com/v2/checkout/orders/3L413397YW525633X",
        "rel": "self",
        "method": "GET"
      }
    ],
    "id": "3L413397YW525633X",
    "intent": "CAPTURE",
    "payer": {
      "name": {
        "given_name": "jihua",
        "surname": "gao"
      },
      "email_address": "biz1@china.com",
      "payer_id": "4TQJ57BB6MXBA",
      "address": {
        "country_code": "C2"
      }
    },
    "status": "COMPLETED"
  },
  "links": [
    {
      "href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-0H899151972497740-0A372964B8753370B",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-0H899151972497740-0A372964B8753370B/resend",
      "rel": "resend",
      "method": "POST"
    }
  ]
}

###

POST http://127.0.0.1:8080/payment/paypal/notify
Content-Type: applications/json

{
  "id": "WH-9T01149574387741W-8HS93032RC216262D",
  "event_version": "1.0",
  "create_time": "2020-12-02T11:00:38.101Z",
  "resource_type": "capture",
  "resource_version": "2.0",
  "event_type": "PAYMENT.CAPTURE.PENDING",
  "summary": "Payment pending for EUR 4804.74 EUR",
  "resource": {
    "amount": {
      "value": "4804.74",
      "currency_code": "EUR"
    },
    "seller_protection": {
      "dispute_categories": [
        "ITEM_NOT_RECEIVED",The sender of this payment is Verified
    },
    "update_time": "2020-12-02T11:00:18Z",
    "create_time": "2020-12-02T11:00:18Z",
    "final_capture": true,
    "invoice_id": "20201263800",
    "links": [
      {
        "method": "GET",
        "rel": "self",
        "href": "https://api.sandbox.paypal.com/v2/payments/captures/3LD69008R86142613"
      },
      {
        "method": "POST",
        "rel": "refund",
        "href": "https://api.sandbox.paypal.com/v2/payments/captures/3LD69008R86142613/refund"
      },
      {
        "method": "GET",
        "rel": "up",
        "href": "https://api.sandbox.paypal.com/v2/checkout/orders/15A2920554687094S"
      }
    ],
    "id": "3LD69008R86142613",
    "status_details": {
      "reason": "RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION"
    },
    "status": "PENDING"
  },
  "links": [
    {
      "href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-9T01149574387741W-8HS93032RC216262D",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-9T01149574387741W-8HS93032RC216262D/resend",
      "rel": "resend",
      "method": "POST"
    }
  ]
}

###
POST http://127.0.0.1:8080/api/v1/login 
Content-Type: applications/json

{"email":"lq@163.com","password":"123456"}

###


POST http://127.0.0.1:8080/api/v1/user/update
Content-Type: applications/json
Set-Cookie: lqcms_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOm51bGwsImNvdW50cnkiOiIiLCJleHAiOiIyMDIwLTEyLTAxVDEzOjI5OjM5LjQ2NDUyODE2MSswODowMCIsImlhdCI6bnVsbCwiaXNzIjpudWxsLCJqdGkiOm51bGwsIm5iZiI6bnVsbCwic3ViIjpudWxsLCJ1c2VyIjoibHFAMTYzLmNvbSJ9.UX7uGXv3hgkpAGNJ8gC5yl1XhkAxrLLftP6GjlDpCXI

{"email":"lq@163.com","new_password":"1","social_link":"ab@cd.om","social_type":"twitter"}

###

POST http://127.0.0.1:8080/api/v1/logout 
Content-Type: applications/json
Set-Cookie: lqcms_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOm51bGwsImNvdW50cnkiOiIiLCJleHAiOiIyMDIwLTEyLTAxVDEzOjA0OjMyLjgzNDgwODYxNSswODowMCIsImlhdCI6bnVsbCwiaXNzIjpudWxsLCJqdGkiOm51bGwsIm5iZiI6bnVsbCwic3ViIjpudWxsLCJ1c2VyIjoibHFAMTYzLmNvbSJ9.d_TPWHHmU2AkfILpxue9zPGpO2BFmmC93FpP5fhkQsg

###


GET http://127.0.0.1:8080/payment/paypal/info/27
Content-Type: applications/json