POST  http://view.bk.cloudns.cc:8080/admin/v1/login
HEAD: "Content-Type: applications/json"

{
    "email":"lq@163.com",
    "password":"qweasdzxc"
}

### to login paypal site

post https://api.sandbox.paypal.com/v1/oauth2/token
Content-Type: applications/json
Accept-Language: en-US
Authorization: Basic AbOMcM4iaf0PYKGgOFCktDD-Rqzpn7R_r2yPfwbopgCLYkBLXkD45c1qejwVX2BrBSxVQgz3_QlU7iFn:EKxToL0apcJ7HOAryLeFkyP9JRWuw-p8pMj9M5N3Y1Ee8tsUDFgRv1wA_3hIjRMiHqrmbQu12KW_Noys

grant_type=client_credentials

### 

curl -v -X GET https://api.sandbox.paypal.com/v1/notifications/webhooks \
-H "Content-Type: application/json" \
-H "Authorization: Bearer A21AAGqrGSBqpmkje73inCzBSAsSAFODksGVwUR0cueljujz32t1iwpdw5TD2Li2sgF-Cz5EEs70hsq4TE02OAi1eDNjfjSyw



### send the get user info

GET https://api.sandbox.paypal.com/v1/identity/oauth2/userinfo?schema=paypalv1.1
Content-Type: application/json
Authorization: Bearer A21AAHW1QOVoF8XXCjXd1SZsmdkvR-167eqKwBotihG7O57ylCL6RMWJxxyjVaEsdp8Wk7dqpjvSwrRZU5mAnOm_aYo3ZWDJA 

###
GET https://api.sandbox.paypal.com/v1/notifications/webhooks/8GJ36790KA152731C
Content-Type: application/json
Authorization: Bearer A21AAHW1QOVoF8XXCjXd1SZsmdkvR-167eqKwBotihG7O57ylCL6RMWJxxyjVaEsdp8Wk7dqpjvSwrRZU5mAnOm_aYo3ZWDJA 


### create a order capture

POST https://api.sandbox.paypal.com/v2/checkout/orders 
Content-Type: application/json
Authorization: Bearer A21AAGjisTyiOixUgpyPa-YReTwmI5f6LeXHm2FF1B4OYG-0RhRKwiznAPFfRy9MUkBUsh7SPLTfw9UMV6N0_rV9c5_X3rOjQ

{
  "intent": "CAPTURE",
  "purchase_units": [
    {
      "amount": {
        "currency_code": "USD",
        "value": "100.00"
      }
    }
  ]
}

###

POST https://api.sandbox.paypal.com/v1/payments/payment
Content-Type: application/json
Authorization: Bearer A21AAGjisTyiOixUgpyPa-YReTwmI5f6LeXHm2FF1B4OYG-0RhRKwiznAPFfRy9MUkBUsh7SPLTfw9UMV6N0_rV9c5_X3rOjQ

{
  "intent": "sale",
  "payer": {
    "payment_method": "paypal"
  },
  "transactions": [
    {
      "amount": {
        "total": "30.11",
        "currency": "USD",
        "details": {
          "subtotal": "30.00",
          "tax": "0.07",
          "shipping": "0.03",
          "handling_fee": "1.00",
          "shipping_discount": "-1.00",
          "insurance": "0.01"
        }
      },
      "description": "The payment transaction description.",
      "custom": "Eabc122334",
      "invoice_number": "2233334443232",
      "payment_options": {
        "allowed_payment_method": "INSTANT_FUNDING_SOURCE"
      },
      "soft_descriptor": "Esdsfsfs",
      "item_list": {
        "items": [
          {
            "name": "hat",
            "description": "Brown hat.",
            "quantity": "5",
            "price": "3",
            "tax": "0.01",
            "sku": "1",
            "currency": "USD"
          },
          {
            "name": "handbag",
            "description": "Black handbag.",
            "quantity": "1",
            "price": "15",
            "tax": "0.02",
            "sku": "product34",
            "currency": "USD"
          }
        ],
        "shipping_address": {
          "recipient_name": "Brian Robinson",
          "line1": "4th Floor",
          "line2": "Unit #34",
          "city": "San Jose",
          "country_code": "US",
          "postal_code": "95131",
          "phone": "011862212345678",
          "state": "CA"
        }
      }
    }
  ],
  "note_to_payer": "Contact us for any questions on your order.",
  "redirect_urls": {
    "return_url": "https://view.bk.cloudns.cc:9090/return",
    "cancel_url": "https://view.bk.cloudns.cc:9090/cancel"
  }
}

###

POST http://127.0.0.1:8080/payment/paypal/pay
Content-Type: application/json

{
  "payer":"paypal",
  "email":"jihua.gao@mgmail.com",
  "amount":{
        "value": "30.11",
        "currency_code": "USD"
  },
  "shipping": {
      "recipient_name": "Brian Robinson",
      "line1": "4th Floor",
      "line2": "Unit #34",
      "city": "San Jose",
      "country_code": "US",
      "postal_code": "95131",
      "phone": "011862212345678",
      "state": "CA"
    },
  "item_list": [
          {
            "name": "hat",
            "description": "Brown hat.",
            "unit_amount": "5",
            "quantity": "5",
            "price": "30.11",
            "currency": "USD"
          }
  ]  
}

###


POST http://view.bk.cloudns.cc:8080/payment/paypal/pay
Content-Type: application/json

{
  "payer":"paypal",
  "email":"jihua.gao@mgmail.com",
  "item_list": [
        {
          "amount":{
                "value": "30.11",
                "currency_code": "USD",
                "breakdown":{
                  "item_total":{
                    "currency_code":"USD",
                    "value":"30.11"
                  }
                }
          },
          "invoice_id":"xzzzzzz2323",
          "description":"note",
          "shipping": {
            "name": {
              "full_name":"Brian Robinson"
            },
            "address":{
              "address_line_1": "4th Floor",
              "address_line_2":"",
              "admin_area_2": "San Jose",
              "admin_area_1": "CA",
              "country_code": "US",
              "postal_code":"300984"
            }
          },
          "items":[
          {
            "name": "hat111",
            "description": "Brown hat. for human",
            "unit_amount":{
              "currency_code":"USD",
              "value":"3"
            },
            "quantity": "5",
            "category": "DIGITAL_GOODS"
          },
          {
            "name": "handbag222",
            "description": "Black handbag. for spagati",
            "quantity": "1",
            "unit_amount":{
              "currency_code":"USD",
              "value":"15.11"
            },
            "category": "DIGITAL_GOODS"
          }
          ]
        }
  ] 
}

###

POST http://127.0.0.1:8080/payment/paypal/pay
Content-Type: application/json

{
  "payer":"paypal",
  "email":"jihua.gao@mgmail.com",
  "amount":{
        "value": "30.11",
        "currency_code": "USD",
        "breakdown":{
          "item_total":{
            "currency_code":"USD",
            "value":"30.11"
          }
        }
  },
  "shipping": {
      "recipient_name": "Brian Robinson",
      "line1": "4th Floor",
      "city": "San Jose",
      "country_code": "US",
      "postal_code":"300984"
    },
  "item_list": [
          { 
            "name": "hat111",
            "description": "Brown hat.",
            "unit_amount":{
              "currency_code":"USD",
              "value":"3"
            },
            "quantity": 5,
            "category": "DIGITAL_GOODS"
          },
          {
            "name": "handbag222",
            "description": "Black handbag.",
            "quantity": 1,
            "unit_amount":{
              "currency_code":"USD",
              "value":"15"
            },
            "category": "DIGITAL_GOODS"
          }
  ]  
}


###

POST http://127.0.0.1:8080/admin/v1/login 
Content-Type: applications/json

{"email":"jihua.gao@gmail.com","password":"qweasdzxc"}

###

POST http://127.0.0.1:8080/admin/v1/content?type=Game 
Content-Type: applications/json
Set-Cookie: lqcms_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOm51bGwsImV4cCI6IjIwMjAtMDUtMjdUMTQ6NDM6MDAuNDgyOTEwNjk3KzA4OjAwIiwiaWF0IjpudWxsLCJpc3MiOm51bGwsImp0aSI6bnVsbCwibmJmIjpudWxsLCJzdWIiOm51bGwsInVzZXIiOiJqaWh1YS5nYW9AZ21haWwuY29tIn0.e6X2YLQvyeU2L3xxlgpphVKKX5dKVQuH6qCLHCWhNF0; Path=/; Expires=Wed, 27 May 2020 06:43:00 GMT

{"logo":2,"longlogo":"aa","online":false,"name":"测试2","sname":"ce","description":"<div>sldek</div>"}

###


POST http://sandbox.payssion.com/api/v1/payment/create
Content-Type: applications/json

{"api_key":"sandbox_5dea43e2a2a8e257",
"pm_id":"dotpay_pl",
"amount":"1",
"currency":"USD",
"description":"payment description",
"order_id":"1234",
"api_sig":"add918417e849e1e8c350c3babe3c6d7"
}


###


POST http://view.bk.cloudns.cc:8080/payment/payssion/pay
Content-Type: applications/json

{
"pm_id":"dotpay_pl",
"amount":"221",
"currency":"USD",
"description":"神奇宝贝"
}




### 

POST http://127.0.0.1:8080/payment/payssion/pay
Content-Type: applications/json

{
"pm_id":"dotpay_pl",
"amount":"333",
"currency":"USD",
"description":"riptifdsafsafasfdsadfsafdon"
}

### 
POST http://127.0.0.1:8080/payment/payssion/notify
Content-Type: applications/json

{
  "app_name": "eshop",
"pm_id": "dotpay_pl",
"transaction_id": "T527553600236576",
"order_id" :"cf6ff489dc1cb799987fa989c6f41d45",
"amount":"12.00",
"currency":"USD",
"state":"completed",
"notify_sig": "addDSAasfsafdaasdf"
}

### 

POST http://127.0.0.1:8080/payment/paypal/notify
Content-Type: application/json

{
  "id": "WH-58D329510W468432D-8HN650336L201105X",
  "create_time": "2019-02-14T21:50:07.940Z",
  "resource_type": "capture",
  "event_type": "PAYMENT.CAPTURE.COMPLETED",
  "summary": "Payment completed for $ 2.51 USD",
  "resource": {
    "amount": {
      "currency_code": "USD",
      "value": "2.51"
    },
    "seller_protection": {
      "status": "ELIGIBLE",
      "dispute_categories": [
        "ITEM_NOT_RECEIVED",
        "UNAUTHORIZED_TRANSACTION"
      ]
    },
    "update_time": "2019-02-14T21:49:58Z",
    "create_time": "2019-02-14T21:49:58Z",
    "final_capture": true,
    "seller_receivable_breakdown": {
      "gross_amount": {
        "currency_code": "USD",
        "value": "2.51"
      },
      "paypal_fee": {
        "currency_code": "USD",
        "value": "0.37"
      },
      "net_amount": {
        "currency_code": "USD",
        "value": "2.14"
      }
    },
    "links": [
      {
        "href": "https://api.paypal.com/v2/payments/captures/27M47624FP291604U",
        "rel": "self",
        "method": "GET"
      },
      {
        "href": "https://api.paypal.com/v2/payments/captures/27M47624FP291604U/refund",
        "rel": "refund",
        "method": "POST"
      },
      {
        "href": "https://api.paypal.com/v2/payments/authorizations/7W5147081L658180V",
        "rel": "up",
        "method": "GET"
      }
    ],
    "id": "27M47624FP291604U",
    "status": "COMPLETED"
  },
  "links": [
    {
      "href": "https://api.paypal.com/v1/notifications/webhooks-events/WH-58D329510W468432D-8HN650336L201105X",
      "rel": "self",
      "method": "GET",
      "encType": "application/json"
    },
    {
      "href": "https://api.paypal.com/v1/notifications/webhooks-events/WH-58D329510W468432D-8HN650336L201105X/resend",
      "rel": "resend",
      "method": "POST",
      "encType": "application/json"
    }
  ],
  "event_version": "1.0",
  "resource_version": "2.0"
}

###

POST http://view.bk.cloudns.cc:8080/payment/skrill/pay
Content-Type: application/json

{
"amount":"2.2",
"currency":"EUR",
"description":"riptifdsafsafasfdsadfsafdon",
"payer_email":"18901882538@189.cn",
"address":"天色一万",
"city":"上海",
"country":"以色列",
"description":"机关枪3把"
}


###

POST  https://pay.skrill.com/?prepare_only=1&pay_to_email=demoqco@sun-fish.com&language=EN&amount=3.2&currency=GBP&detail1_description=helloworld&detail1_text=mm
Content-Type: application/x-www-form-urlencoded
      

														<a target="_blank" href="https://www.skrill.com/en/business/integration/">
															<img src="https://www.skrill.com/fileadmin/content/images/brand_centre/Payment_Options_by_Skrill/skrill-powered-visa_120x60.png" alt="Visa by Skrill" title="Visa by Skrill"/>
														</a>

												
